# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: joshka.net
tagline: Josh McKinney
email: joshka.blog2016@no.spam.joshka.net
description: > # this means to ignore newlines until "baseurl:"
  The homepage of Joshua McKinney.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.joshka.net" # the base hostname & protocol for your site
twitter_username: joshuamck
github_username: joshka
linkedin_username: joshuamckinney
soundcloud_username: joshka
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
