# The URL the site will be built for
base_url = "https://joshka.net"

# The site title and description; used in feeds by default.
title = "Joshka.net"
description = "Josh McKinney's personal website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# https://www.getzola.org/themes/zola-theme-terminimal/
theme = "terminimal"

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "boron"

[extra]
# Put all your custom variables here

# The logo text - defaults to "Terminimal theme"
logo_text = "Joshka.net"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Josh McKinney"

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
# background_color = "blue-auto"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "combined"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    { name = "blog", url = "$BASE_URL" },

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    # { name = "tags", url = "$BASE_URL/tags" },
    { name = "archive", url = "$BASE_URL/archive" },
    { name = "about me", url = "$BASE_URL/about" },
    { name = "resume", url = "$BASE_URL/resume" },
    { name = "projects", url = "$BASE_URL/projects" },

    # set newtab to true to make the link open in new tab
    { name = "github", url = "https://github.com/joshka", newtab = true },
    # { name = "linked-in", url = "https://linkedin.com/in/joshuamckinney", newtab = true },
    { name = "mastodon", url = "https://hachyderm.io/@joshka", newtab = true },
    { name = "soundcloud", url = "https://soundcloud.com/joshka", newtab = true },

]
